=== AmparoFernandez/EjerciciosLMSGI/Examenes resueltos/Examen01.dtd
<!ELEMENT videoclub (peliculas, ofertas)>
<!ELEMENT peliculas (pelicula)>
<!ELEMENT ofertas (oferta*)>
<!ELEMENT pelicula (nombre, genero, precio, (disponible | alquilada))>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT precio EMPTY>
<!ELEMENT disponible EMPTY>
<!ELEMENT alquilada EMPTY>
<!ELEMENT oferta (#PCDATA | platoReferido)*>
<!ELEMENT platoReferido ANY>
<!ATTLIST restaurante direccion CDATA #IMPLIED 
                      nombre CDATA #REQUIRED
                      telefono CDATA #FIXED "957591456">
<!ATTLIST pelicula codigo ID #REQUIRED
                ingredientePrincipal (queso | frijoles | chile) "queso">
<!ATTLIST peliculaReferida codigoPelicula IDREF #REQUIRED
                        bonoPareja IDREFS #IMPLIED>
<!ENTITY % atributoCoste "coste CDATA #IMPLIED"> 
<!ATTLIST precio %atributoCoste;>
<!ATTLIST oferta %atributoCoste;>
<!ENTITY picante "tres jalapeÃ±os">

=== AmparoFernandez/EjerciciosLMSGI/Examenes resueltos/Examen01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videoclub SYSTEM "Examen01.dtd">
<videoclub direccion="Calle La Patica" nombre="Sensacine" telefono="957405033">
  <peliculas>
    <pelicula codigo="her" ingredientePrincipal="queso">
      <nombre> Hércules </nombre>
      <genero> Fantasía </genero>
      <precio coste="10" />
      <alquilada/>
    </pelicula>
    <pelicula codigo="ins">
      <nombre> Insidious </nombre>
      <genero> Terror </genero>
      <precio coste="7" />
      <disponible/>
    </pelicula>
  </platos>
  <ofertas>
    <oferta coste="15">2x1 
      <peliculaReferida codigoPelicula="ques" bonoPareja="her ins" />
    </oferta>
  </ofertas>
  </peliculas>
