=== AmparoFernandez/EjerciciosLMSGI/Examenes resueltos/Prueba.dtd
<!ELEMENT videoclub (peliculas, juegos)>
<!ELEMENT peliculas (pelicula+)>
<!ELEMENT pelicula (nombre, extranjera?, genero, precio, (disponible | agotada))>
<!ELEMENT disponible EMPTY>    
<!ELEMENT agotada EMPTY>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT precio (#PCDATA)> 
<!ELEMENT extranjera EMPTY>
<!ELEMENT oferta (#PCDATA | peliculasReferidas)*>
<!ELEMENT peliculasReferidas ANY>
<!ELEMENT ofertas (#PCDATA)>

=== AmparoFernandez/EjerciciosLMSGI/Examenes resueltos/Prueba.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videoclub SYSTEM "Prueba.dtd">

<videoclub nombre= Sensacine direccion= Calle La Patica telefono= 9576606070>
    <peliculas>
<pelicula>
    <nombre> Big Hero Six </nombre>
    <extranjera />
    <genero> Fantasía </genero>
    <precio> 6 </precio>
    <disponible />
</pelicula>
<pelicula>
    <nombre> Rompe Ralph </nombre>
    <extranjera />
    <genero> Fantasía </genero>
    <precio> 6 </precio>
    <alquilada />
</pelicula>
<ofertas></ofertas>
    </peliculas>
















</videoclub>
