=== AmparoFernandez/EjerciciosLMSGI/Examenes/DTD/Examen.dtd
<!ELEMENT horarios (tren, ofertas)>
<!ELEMENT tren (vagon+)>
<!ELEMENT ofertas (oferta*)>
<!ELEMENT vagon (hora, destino, permiteAnimales?, precio, (mañana | tarde))>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT destino (#PCDATA)>
<!ELEMENT permiteAnimales EMPTY>
<!ELEMENT precio EMPTY>
<!ELEMENT mañana EMPTY>
<!ELEMENT tarde EMPTY>
<!ELEMENT oferta (#PCDATA | descuentoEstudiantes)*>
<!ELEMENT descuentoEstudiantes ANY>
<!ATTLIST horarios empresa CDATA #IMPLIED
                      dirección CDATA #REQUIRED
                      telefono CDATA #FIXED "957609066">
<!ATTLIST vagon codigo ID #REQUIRED
                numeroVagon (1 | 2 | 3) "1">
<!ATTLIST descuentoEstudiantes codigoVagon IDREF #REQUIRED
                        packAhorro IDREFS #IMPLIED>
<!ENTITY % atributoCoste "coste CDATA #IMPLIED"> 
<!ATTLIST precio %atributoCoste;>
<!ATTLIST oferta %atributoCoste;>
<!ENTITY trasbordo "Hace trasbordo durante el viaje">

=== AmparoFernandez/EjerciciosLMSGI/Examen DTD/Examen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE horarios SYSTEM "Examen.dtd">
<horarios empresa="Renfe" dirección="Calle Gran Avenida" telefono="957609066">
  <tren>
    <vagon codigo="vag1" numeroVagon="1">
      <hora> 8.00 am &trasbordo;</hora>
      <destino> Madrid </destino>
      <permiteAnimales/>
      <precio coste="25" />
      <mañana />
    </vagon>
    <vagon codigo="vag2" numeroVagon="2">
      <hora> 18.00 pm </hora>
      <destino> Barcelona </destino>
      <precio coste="50" />
      <tarde />
    </vagon>
  </tren>
  <ofertas>
    <oferta coste="30">2x1 
        <descuentoEstudiantes codigoVagon="vag1" packAhorro="vag1 vag2" />
      </oferta>
    </ofertas>
</horarios>
