=== AmparoFernandez/EjerciciosLMSGI/Ejercicios XSD/personajesDisney.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="disney" type="tipoDisney"/>

  <xs:complexType name="tipoDisney" mixed="true">
    <xs:all>
      <xs:element name="pelicula" type="tipoPelicula"/>
      <xs:element name="produccion" type="tipoProduccion"/>
    </xs:all>
  </xs:complexType>

<xs:complexType name="tipoPelicula">
  <xs:sequence>
    <xs:element name="protagonistas" type="tipoProtagonista" maxOccurs="unbounded"/>
    <xs:element name="antagonistas" type="tipoAntagonista" maxOccurs="unbounded"/>
  </xs:sequence>
  <xs:attribute name="nombre" type="xs:string"/>
  <xs:attribute name="countPersonajes" type="xs:integer"/>
</xs:complexType>

<xs:complexType name="tipoAntagonista">
  <xs:attribute name="nombre" type="xs:string"/>
  <xs:attribute name="experimento" type="tipoExperimento"/>
  <xs:attribute name="nacionalidad" type="tipoNacionalidades"/>
</xs:complexType>

<xs:simpleType name="tipoExperimento">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{3}"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="tipoNacionalidadHawaiana">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Estadounidense"/>
      <xs:enumeration value="Hawaiana"/>
    </xs:restriction>
  </xs:simpleType>

<xs:simpleType name="tipoNacionalidadExtraterrestre">
  <xs:restriction base="xs:string">
    <xs:enumeration value="Extraterrestre"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="tipoNacionalidad">
    <xs:union memberTypes="tipoNacionalidadHawaiana tipoNacionalidadExtraterrestre"/>
</xs:simpleType>

<xs:simpleType name="tipoNacionalidades">
  <xs:list itemType="tipoNacionalidad"/>
</xs:simpleType>

<xs:complexType name="tipoProtagonista">
  <xs:complexContent>
    <xs:extension base="tipoAntagonista"/>
  </xs:complexContent>
</xs:complexType>

<xs:complexType name="tipoProduccion">
  <xs:sequence>
    <xs:element name="animacion" type="tipoAnimacion" maxOccurs="1"/>  
    <xs:element name="estreno" type="tipoEstreno" maxOccurs="1"/> 
  </xs:sequence>
</xs:complexType>

<xs:complexType name="tipoAnimacion">
    <xs:choice>
      <xs:element name="animada" type="tipoAnimada"/>
      <xs:element name="realista" type="tipoRealista"/>
    </xs:choice>
    <xs:attribute name="nombre" type="xs:string"/>
  </xs:complexType>

  <xs:simpleType name="numericoEntre2002y2023">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="2002"/>
      <xs:maxInclusive value="2023"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="tipoEstreno">
    <xs:simpleContent>
      <xs:extension base="numericoEntre2002y2023">
        <xs:attribute name="anio"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="tipoAnimada">
  </xs:complexType>

  <xs:complexType name="tipoRealista">
  </xs:complexType>

</xs:schema>

=== AmparoFernandez/EjerciciosLMSGI/Ejercicios/XSD/personajesDisney.xml
<?xml version="1.0" encoding="UTF-8"?>
<disney xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="personajesDisney.xsd">
 Un montón de personajes Disney
 <pelicula nombre="Lilo y Stitch" countPersonajes="3">
  <protagonistas nombre="Lilo" nacionalidad="Hawaiana"/>
  <protagonistas nombre="Stitch" nacionalidad="Extraterrestre" experimento= "626"/>
  <protagonistas nombre="Dr.Jumba" nacionalidad="Extraterrestre"/>
  <antagonistas nombre="Reuben" nacionalidad="Extraterrestre" experimento="625"/>
  <antagonistas nombre="Gantu" nacionalidad="Extraterrestre"/>
 </pelicula>
 <produccion>
    <animacion>
      <animada/>
  </animacion>
  <estreno> 2020 </estreno>
 </produccion>
</disney>
